on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

name: lint and test

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  unit-tests:
    needs: [pre-commit]
    name: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          # Install a specific version of uv.
          version: "0.4.26"

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync

      - name: Run coverage
        run: uv run pytest --cov-report=xml:coverage.xml --cov=pycoingecko/ tests/

      - name: Codecov
        if: success()
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage.xml
          flags: unittests-py${{ matrix.python-version }}

      # - name: Publish to PyPi
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: uv build && uv publish
      #   env:
      #     UV_PUBLISH_TOKEN: ${{ secrets.PYPI_RELEASE_TOKEN }}

  create-release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: [unit-tests]
    uses: nickatnight/gha-workflows/.github/workflows/create-release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
